language: python
os: linux
dist: focal
cache: false
install:
  - travis_retry pip install -U tox-travis
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38
    - python: 3.9-dev
      env: TOXENV=py39
    - python: 3.7
      env: TOXENV=flake8
script: tox -v -- -v
