language: python
os: linux
dist: focal
cache: false
install:
  - travis_retry pip install -U tox-travis
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
      dist: xenial
    - python: 3.7
      env: TOXENV=py37
      dist: bionic
    - python: 3.8-dev
      env: TOXENV=py38
      dist: focal
    - python: 3.7
      env: TOXENV=flake8
      dist: focal
script: tox -v -- -v
